package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 11-12-2014 09:30:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Familiar generated by hbm2java
 */
@Entity
@Table(name = "familiar", catalog = "scnpalas")
@NamedQueries({
	@NamedQuery(name="Familiar.findByAll", query="SELECT a FROM Familiar a"),
	@NamedQuery(name="Familiar.findByIdent", query="SELECT a FROM Familiar a WHERE a.ident = :id")/*,
	@NamedQuery(name="Familiar.findByAlumno", query="SELECT a FROM Familiar a, Familiares b WHERE a.ident = b.familiar AND b.alumno = :alumno")*/
	})
public class Familiar implements java.io.Serializable {

	private Integer ident;
	private Usuario usuario;
	private String nombre;
	private String direccion;
	private String telefono;
	private String celular;
	private String empresa;
	private String email;
	private String lugtrabajo;
	private String dirtrabajo;
	private String teltrabajo;
	private String exttrabajo;
	private Integer parentesco;
	private Set<Familiares> familiareses = new HashSet<Familiares>(0);

	public Familiar() {
		this.nombre = "";
		this.direccion = "";
		this.telefono = "";
		this.celular = "";
		this.empresa = "";
		this.email = "";
		this.lugtrabajo = "";
		this.dirtrabajo = "";
		this.teltrabajo = "";
		this.exttrabajo = "";
	}

	public Familiar(Usuario usuario) {
		this.usuario = usuario;
	}

	public Familiar(Usuario usuario, String nombre, String direccion,
			String telefono, String celular, String empresa, String email,
			String lugtrabajo, String dirtrabajo, String teltrabajo,
			String exttrabajo, Integer parentesco, Set<Familiares> familiareses) {
		this.usuario = usuario;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.celular = celular;
		this.empresa = empresa;
		this.email = email;
		this.lugtrabajo = lugtrabajo;
		this.dirtrabajo = dirtrabajo;
		this.teltrabajo = teltrabajo;
		this.exttrabajo = exttrabajo;
		this.parentesco = parentesco;
		this.familiareses = familiareses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", length = 500)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "celular", length = 45)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "empresa", length = 45)
	public String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "lugtrabajo", length = 100)
	public String getLugtrabajo() {
		return this.lugtrabajo;
	}

	public void setLugtrabajo(String lugtrabajo) {
		this.lugtrabajo = lugtrabajo;
	}

	@Column(name = "dirtrabajo", length = 500)
	public String getDirtrabajo() {
		return this.dirtrabajo;
	}

	public void setDirtrabajo(String dirtrabajo) {
		this.dirtrabajo = dirtrabajo;
	}

	@Column(name = "teltrabajo", length = 45)
	public String getTeltrabajo() {
		return this.teltrabajo;
	}

	public void setTeltrabajo(String teltrabajo) {
		this.teltrabajo = teltrabajo;
	}

	@Column(name = "exttrabajo", length = 5)
	public String getExttrabajo() {
		return this.exttrabajo;
	}

	public void setExttrabajo(String exttrabajo) {
		this.exttrabajo = exttrabajo;
	}

	@Column(name = "parentesco")
	public Integer getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(Integer parentesco) {
		this.parentesco = parentesco;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familiar")
	public Set<Familiares> getFamiliareses() {
		return this.familiareses;
	}

	public void setFamiliareses(Set<Familiares> familiareses) {
		this.familiareses = familiareses;
	}

}
