package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 11-12-2014 09:30:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Grado generated by hbm2java
 */
@Entity
@Table(name = "grado", catalog = "scnpalas")
@NamedQueries({
	@NamedQuery(name = "Grado.findByAll", query = "SELECT c FROM Grado c "),
	@NamedQuery(name = "Grado.findByIdent", query = "SELECT c FROM Grado c WHERE ident = :id")
})
public class Grado implements java.io.Serializable {

	private Integer ident;
	private Seccion seccion;
	private Periodo periodo;
	private Docente docente;
	private int inscritos;
	private String estado;
	private Set<Matricula> matriculas = new HashSet<Matricula>(0);
	private Set<GradoMateria> gradoMaterias = new HashSet<GradoMateria>(0);

	public Grado() {
		this.ident = 0;
	}

	public Grado(Seccion seccion, Periodo periodo, Docente docente,
			int inscritos, String estado) {
		this.seccion = seccion;
		this.periodo = periodo;
		this.docente = docente;
		this.inscritos = inscritos;
		this.estado = estado;
	}

	public Grado(Seccion seccion, Periodo periodo, Docente docente,
			int inscritos, String estado, Set<Matricula> matriculas,
			Set<GradoMateria> gradoMaterias) {
		this.seccion = seccion;
		this.periodo = periodo;
		this.docente = docente;
		this.inscritos = inscritos;
		this.estado = estado;
		this.matriculas = matriculas;
		this.gradoMaterias = gradoMaterias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seccion", nullable = false)
	public Seccion getSeccion() {
		return this.seccion;
	}

	public void setSeccion(Seccion seccion) {
		this.seccion = seccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "periodo", nullable = false)
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "inscritos", nullable = false)
	public int getInscritos() {
		return this.inscritos;
	}

	public void setInscritos(int inscritos) {
		this.inscritos = inscritos;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grado")
	public Set<Matricula> getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set<Matricula> matriculas) {
		this.matriculas = matriculas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grado")
	public Set<GradoMateria> getGradoMaterias() {
		return this.gradoMaterias;
	}

	public void setGradoMaterias(Set<GradoMateria> gradoMaterias) {
		this.gradoMaterias = gradoMaterias;
	}
	
	public String toString(){
		return this.periodo.toString()+" "+
			   this.docente.toString()+" "+
			   this.seccion.toString()+" "+
			   this.inscritos;
	}
}
