package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 12-04-2014 11:18:58 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grado generated by hbm2java
 */
@Entity
@Table(name = "grado", catalog = "scnpalas")
public class Grado implements java.io.Serializable {

	private Integer ident;
	private Grado gradoByGrado1;
	private Grado gradoByGrado2;
	private String grado;

	public Grado() {
		this.ident = 0;
		this.grado = "";
	}

	public Grado(String grado) {
		this.grado = grado;
	}

	public Grado(Grado gradoByGrado1, Grado gradoByGrado2, String grado) {
		this.gradoByGrado1 = gradoByGrado1;
		this.gradoByGrado2 = gradoByGrado2;
		this.grado = grado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grado1")
	public Grado getGradoByGrado1() {
		return this.gradoByGrado1;
	}

	public void setGradoByGrado1(Grado gradoByGrado1) {
		this.gradoByGrado1 = gradoByGrado1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grado2")
	public Grado getGradoByGrado2() {
		return this.gradoByGrado2;
	}

	public void setGradoByGrado2(Grado gradoByGrado2) {
		this.gradoByGrado2 = gradoByGrado2;
	}

	@Column(name = "grado", nullable = false, length = 45)
	public String getGrado() {
		return this.grado;
	}

	public void setGrado(String grado) {
		this.grado = grado;
	}
	
	public String toString(){
		return this.grado;
	}

}
