package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 11-12-2014 09:30:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * GradoMateria generated by hbm2java
 */
@Entity
@Table(name = "grado_materia", catalog = "scnpalas")
@NamedQueries({
	@NamedQuery(name = "GradoMateria.findByAll", query = "SELECT c FROM GradoMateria c "),
	@NamedQuery(name = "GradoMateria.findByIdent", query = "SELECT c FROM GradoMateria c WHERE ident = :id")
})
public class GradoMateria implements java.io.Serializable {

	private Integer ident;
	private Grado grado;
	private Materia materia;
	private String enSeccion;
	private Docente docente;
	
	public GradoMateria() {
	}

	public GradoMateria(Grado grado) {
		this.grado = grado;
	}

	public GradoMateria(Grado grado, Materia materia, String enSeccion, Docente docente) {
		this.grado = grado;
		this.materia = materia;
		this.enSeccion = enSeccion;
		this.docente = docente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grado", nullable = false)
	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "materia")
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "en_seccion", length = 1)
	public String getEnSeccion() {
		return this.enSeccion;
	}

	public void setEnSeccion(String enSeccion) {
		this.enSeccion = enSeccion;
	}
	
	public String toString(){
		return this.grado.toString()+" "+
			   this.materia.toString();
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "docente")
	public Docente getDocente() {
		return docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}
}
