package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 11-12-2014 09:30:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "scnpalas")
@NamedQueries({
	@NamedQuery(name = "Log.findByAll", query = "SELECT c FROM Log c "),
	@NamedQuery(name = "Log.findByIdent", query = "SELECT c FROM Log c WHERE ident = :id")
})
public class Log implements java.io.Serializable {

	private Integer ident;
	private Usuario usuario;
	private Date fecha;
	private String tabla;
	private int idTabla;
	private String accion;
	private Set<LogDetalle> logDetalles = new HashSet<LogDetalle>(0);

	public Log() {
	}

	public Log(Usuario usuario, Date fecha, String tabla, int idTabla,
			String accion) {
		this.usuario = usuario;
		this.fecha = fecha;
		this.tabla = tabla;
		this.idTabla = idTabla;
		this.accion = accion;
	}

	public Log(Usuario usuario, Date fecha, String tabla, int idTabla,
			String accion, Set<LogDetalle> logDetalles) {
		this.usuario = usuario;
		this.fecha = fecha;
		this.tabla = tabla;
		this.idTabla = idTabla;
		this.accion = accion;
		this.logDetalles = logDetalles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "tabla", nullable = false, length = 45)
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "id_tabla", nullable = false)
	public int getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(int idTabla) {
		this.idTabla = idTabla;
	}

	@Column(name = "accion", nullable = false, length = 1)
	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "log")
	public Set<LogDetalle> getLogDetalles() {
		return this.logDetalles;
	}

	public void setLogDetalles(Set<LogDetalle> logDetalles) {
		this.logDetalles = logDetalles;
	}

}
