package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 11-21-2014 05:34:49 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolOpciones generated by hbm2java
 */
@Entity
@Table(name = "rol_opciones", catalog = "scnpalas")
public class RolOpciones implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private int ident;
	private Rol rol;
	private String opcion;

	public RolOpciones() {
		this.ident = 0;
	}

	public RolOpciones(int ident, Rol rol, String opcion) {
		this.ident = ident;
		this.rol = rol;
		this.opcion = opcion;
	}

	@Id
	@Column(name = "ident", unique = true, nullable = false)
	public int getIdent() {
		return this.ident;
	}

	public void setIdent(int ident) {
		this.ident = ident;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "opcion", nullable = false, length = 250)
	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

	public String toString(){
		return this.rol.toString()+" "+
			   this.opcion;
	}
}
