package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 11-21-2014 05:34:49 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seccion generated by hbm2java
 */
@Entity
@Table(name = "seccion", catalog = "scnpalas")
public class Seccion implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer ident;
	private Grado grado;
	private Periodo periodo;
	private Docente docente;
	private int inscritos;
	private String estado;
	private String seccion;

	public Seccion() {
		this.ident = 0;
		this.seccion = "";
	}

	public Seccion(Grado grado, Periodo periodo, Docente docente,
			int inscritos, String estado) {
		this.grado = grado;
		this.periodo = periodo;
		this.docente = docente;
		this.inscritos = inscritos;
		this.estado = estado;
	}

	public Seccion(Grado grado, Periodo periodo, Docente docente,
			int inscritos, String estado, String seccion) {
		this.grado = grado;
		this.periodo = periodo;
		this.docente = docente;
		this.inscritos = inscritos;
		this.estado = estado;
		this.seccion = seccion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grado", nullable = false)
	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "periodo", nullable = false)
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "docente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "inscritos", nullable = false)
	public int getInscritos() {
		return this.inscritos;
	}

	public void setInscritos(int inscritos) {
		this.inscritos = inscritos;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "seccion", length = 1)
	public String getSeccion() {
		return this.seccion;
	}

	public void setSeccion(String seccion) {
		this.seccion = seccion;
	}

	public String toString(){
		return this.grado.toString()+" "+
			   this.seccion+" ";//+
			   //this.periodo.toString()+" "+
			   //this.docente.toString();
	}
}
