package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 12-02-2014 09:52:31 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SeccionMateria generated by hbm2java
 */
@Entity
@Table(name = "seccion_materia", catalog = "scnpalas")
public class SeccionMateria implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer ident;
	private Seccion seccion;
	private Materia materia;
	private Docente docente;

	public SeccionMateria() {
		this.ident = 0;
	}

	public SeccionMateria(Seccion seccion, Materia materia, Docente docente) {
		this.seccion = seccion;
		this.materia = materia;
		this.docente = docente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@Column(name = "seccion")
	public Seccion getSeccion() {
		return this.seccion;
	}

	public void setSeccion(Seccion seccion) {
		this.seccion = seccion;
	}

	@Column(name = "materia")
	public Materia getMateria() {
		return this.materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	@Column(name = "docente")
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

}
