package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 11-12-2014 09:30:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name = "subperiodo", catalog = "scnpalas")
@NamedQueries({
	@NamedQuery(name = "SubPeriodo.findByAll", query = "SELECT c FROM SubPeriodo c "),
	@NamedQuery(name = "SubPeriodo.findByIdent", query = "SELECT c FROM SubPeriodo c WHERE ident = :id")
})
public class SubPeriodo implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer ident;
	private Periodo periodo;
	private String descripcion;
	private String estado;
	private Date inicio;
	private Date fin;
	private Set<Evaluacion> evaluaciones = new HashSet<Evaluaciones>(0);

	public SubPeriodo() {
		this.ident = 0;
	}

	public SubPeriodo(Periodo periodo, Date inicio, Date fin, String descripcion, String estado) {
		this.periodo = periodo;
		this.inicio = inicio;
		this.fin = fin;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	public SubPeriodo(Periodo periodo, Date inicio, Date fin, String descripcion, String estado, Set<Evaluacion> evaluaciones) {
		this.periodo = periodo;
		this.inicio = inicio;
		this.fin = fin;
		this.descripcion = descripcion;
		this.estado = estado;
		this.evaluaciones = evaluaciones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "periodo", nullable = false)
	public int getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inicio", nullable = false, length = 10)
	public Date getInicio() {
		return this.inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fin", nullable = false, length = 10)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "evaluacion")
	public Set<Evaluacion> getEvaluaciones() {
		return this.evaluaciones;
	}

	public void setEvaluaciones(Set<Evaluacion> evaluaciones) {
		this.evaluaciones = evaluaciones;
	}
	
	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return descripcion;
	}
	
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	public String toString(){
		return descripcion;
	}	
}
