package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 10-21-2014 12:32:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdministradorId generated by hbm2java
 */
@Embeddable
public class AdministradorId implements java.io.Serializable {

	private String ucarnetusuario;
	private String acarnet;

	public AdministradorId() {
	}

	public AdministradorId(String ucarnetusuario, String acarnet) {
		this.ucarnetusuario = ucarnetusuario;
		this.acarnet = acarnet;
	}

	@Column(name = "UCARNETUSUARIO", nullable = false, length = 8)
	public String getUcarnetusuario() {
		return this.ucarnetusuario;
	}

	public void setUcarnetusuario(String ucarnetusuario) {
		this.ucarnetusuario = ucarnetusuario;
	}

	@Column(name = "ACARNET", nullable = false, length = 8)
	public String getAcarnet() {
		return this.acarnet;
	}

	public void setAcarnet(String acarnet) {
		this.acarnet = acarnet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdministradorId))
			return false;
		AdministradorId castOther = (AdministradorId) other;

		return ((this.getUcarnetusuario() == castOther.getUcarnetusuario()) || (this
				.getUcarnetusuario() != null
				&& castOther.getUcarnetusuario() != null && this
				.getUcarnetusuario().equals(castOther.getUcarnetusuario())))
				&& ((this.getAcarnet() == castOther.getAcarnet()) || (this
						.getAcarnet() != null && castOther.getAcarnet() != null && this
						.getAcarnet().equals(castOther.getAcarnet())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUcarnetusuario() == null ? 0 : this.getUcarnetusuario()
						.hashCode());
		result = 37 * result
				+ (getAcarnet() == null ? 0 : this.getAcarnet().hashCode());
		return result;
	}

}
