package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 10-25-2014 12:09:34 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Codalum generated by hbm2java
 */
@Entity
@Table(name = "codalum", catalog = "palasatenea")
@NamedQueries({
	@NamedQuery(name="Codalum.findByAll", query="SELECT a FROM Codalum a"),
	@NamedQuery(name="Codalum.findByIdent", query="SELECT a FROM Codalum a WHERE a.ident = :id"),
	@NamedQuery(name="Codalum.findByAnioCodigo", query="SELECT c FROM Codalum c WHERE c.anio = :anio AND c.codigo = :")
	})
public class Codalum implements java.io.Serializable {

	private Integer ident;
	private String codigo;
	private Integer anio;
	private Integer correlativo;

	public Codalum() {
	}

	public Codalum(String codigo, Integer anio, Integer correlativo) {
		this.codigo = codigo;
		this.anio = anio;
		this.correlativo = correlativo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@Column(name = "codigo", length = 2)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "correlativo")
	public Integer getCorrelativo() {
		return this.correlativo;
	}

	public void setCorrelativo(Integer correlativo) {
		this.correlativo = correlativo;
	}

}
