package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 10-19-2014 01:12:21 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocenteId generated by hbm2java
 */
@Embeddable
public class DocenteId implements java.io.Serializable {

	private String ucarnetusuario;
	private String doccarnet;

	public DocenteId() {
	}

	public DocenteId(String ucarnetusuario, String doccarnet) {
		this.ucarnetusuario = ucarnetusuario;
		this.doccarnet = doccarnet;
	}

	@Column(name = "UCARNETUSUARIO", nullable = false, length = 8)
	public String getUcarnetusuario() {
		return this.ucarnetusuario;
	}

	public void setUcarnetusuario(String ucarnetusuario) {
		this.ucarnetusuario = ucarnetusuario;
	}

	@Column(name = "DOCCARNET", nullable = false, length = 10)
	public String getDoccarnet() {
		return this.doccarnet;
	}

	public void setDoccarnet(String doccarnet) {
		this.doccarnet = doccarnet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocenteId))
			return false;
		DocenteId castOther = (DocenteId) other;

		return ((this.getUcarnetusuario() == castOther.getUcarnetusuario()) || (this
				.getUcarnetusuario() != null
				&& castOther.getUcarnetusuario() != null && this
				.getUcarnetusuario().equals(castOther.getUcarnetusuario())))
				&& ((this.getDoccarnet() == castOther.getDoccarnet()) || (this
						.getDoccarnet() != null
						&& castOther.getDoccarnet() != null && this
						.getDoccarnet().equals(castOther.getDoccarnet())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUcarnetusuario() == null ? 0 : this.getUcarnetusuario()
						.hashCode());
		result = 37 * result
				+ (getDoccarnet() == null ? 0 : this.getDoccarnet().hashCode());
		return result;
	}

}
