package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 10-18-2014 06:33:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Estudiante1Id generated by hbm2java
 */
@Embeddable
public class Estudiante1Id implements java.io.Serializable {

	private String ucarnetusuario;
	private String escarnet;

	public Estudiante1Id() {
	}

	public Estudiante1Id(String ucarnetusuario, String escarnet) {
		this.ucarnetusuario = ucarnetusuario;
		this.escarnet = escarnet;
	}

	@Column(name = "UCARNETUSUARIO", nullable = false, length = 8)
	public String getUcarnetusuario() {
		return this.ucarnetusuario;
	}

	public void setUcarnetusuario(String ucarnetusuario) {
		this.ucarnetusuario = ucarnetusuario;
	}

	@Column(name = "ESCARNET", nullable = false, length = 8)
	public String getEscarnet() {
		return this.escarnet;
	}

	public void setEscarnet(String escarnet) {
		this.escarnet = escarnet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Estudiante1Id))
			return false;
		Estudiante1Id castOther = (Estudiante1Id) other;

		return ((this.getUcarnetusuario() == castOther.getUcarnetusuario()) || (this
				.getUcarnetusuario() != null
				&& castOther.getUcarnetusuario() != null && this
				.getUcarnetusuario().equals(castOther.getUcarnetusuario())))
				&& ((this.getEscarnet() == castOther.getEscarnet()) || (this
						.getEscarnet() != null
						&& castOther.getEscarnet() != null && this
						.getEscarnet().equals(castOther.getEscarnet())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUcarnetusuario() == null ? 0 : this.getUcarnetusuario()
						.hashCode());
		result = 37 * result
				+ (getEscarnet() == null ? 0 : this.getEscarnet().hashCode());
		return result;
	}

}
