package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 10-18-2014 06:33:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Grado generated by hbm2java
 */
@Entity
@Table(name = "grado", catalog = "palasatenea")
public class Grado implements java.io.Serializable {

	private String gcodgrado;
	private String gcodprofresponsabE;
	private String gseccion;
	private Set<Estudiante1> estudiante1s = new HashSet<Estudiante1>(0);

	public Grado() {
	}

	public Grado(String gcodgrado, String gcodprofresponsabE, String gseccion) {
		this.gcodgrado = gcodgrado;
		this.gcodprofresponsabE = gcodprofresponsabE;
		this.gseccion = gseccion;
	}

	public Grado(String gcodgrado, String gcodprofresponsabE, String gseccion,
			Set<Estudiante1> estudiante1s) {
		this.gcodgrado = gcodgrado;
		this.gcodprofresponsabE = gcodprofresponsabE;
		this.gseccion = gseccion;
		this.estudiante1s = estudiante1s;
	}

	@Id
	@Column(name = "GCODGRADO", unique = true, nullable = false, length = 10)
	public String getGcodgrado() {
		return this.gcodgrado;
	}

	public void setGcodgrado(String gcodgrado) {
		this.gcodgrado = gcodgrado;
	}

	@Column(name = "GCODPROFRESPONSAB_E", nullable = false, length = 10)
	public String getGcodprofresponsabE() {
		return this.gcodprofresponsabE;
	}

	public void setGcodprofresponsabE(String gcodprofresponsabE) {
		this.gcodprofresponsabE = gcodprofresponsabE;
	}

	@Column(name = "GSECCION", nullable = false, length = 2)
	public String getGseccion() {
		return this.gseccion;
	}

	public void setGseccion(String gseccion) {
		this.gseccion = gseccion;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "grados")
	public Set<Estudiante1> getEstudiante1s() {
		return this.estudiante1s;
	}

	public void setEstudiante1s(Set<Estudiante1> estudiante1s) {
		this.estudiante1s = estudiante1s;
	}

}
