package sv.edu.ues.dsi.palasatenea.modelo;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;
/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "materia", catalog = "palasatenea")
@NamedQueries({
	@NamedQuery(name="Materia.findByAll", query="SELECT a FROM materia a"),
	@NamedQuery(name="Materia.findByIdent", query="SELECT a FROM materia WHERE m.ident = :id"),
	@NamedQuery(name="Materia.findByYear", query="SELECT m FROM materia m WHERE m.doccarnet BETWEEN :estcarnet AND :acodano")
	})
public class Materia implements java.io.Serializable {
	private Integer ident;
	private String mcodmateria;
    private String doccarnet;
	private String estcarnet;
	private String acodano;
	
	
	
	public Materia() {
		this.mcodmateria = "";
		
		this.doccarnet = "";
		this.estcarnet = "";
		this.acodano = "";
			}

	public Materia(String mcodmateria,  String doccarnet, String estcarnet,
			String acodano){
	
       this.mcodmateria = "mcodmateria";
		
		this.doccarnet = "doccarnet";
		this.estcarnet = "estcarnet";
		this.acodano = "acodano";
		
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ident", unique = true, nullable = false)
	public Integer getIdent() {
		return this.ident;
	}

	public void setIdent(Integer ident) {
		this.ident = ident;
	}

	@Column(name = "mcodmateria", length = 8)
	public String getCodigo() {
		return this.mcodmateria;
	}

	public void setmcodmateria(String mcodmateria) {
		this.mcodmateria= mcodmateria;
	}

	@Column(name = "doccarnet",length =8)
	public String getdoccarnet() {
		return this.doccarnet;
	}

	public void setdoccarnet(String doccarnet) {
		this.doccarnet = doccarnet;
	}

	@Column(name = "estcarnet", length = 50)
	public String getestcarnet() {
		return this.estcarnet;
	}
	public void setestcarnet(String estcarnet) {
		this.estcarnet = estcarnet;
	}

	@Column(name = "acodano", length = 50)
	public String getacodano() {
		return this.acodano;
	}

	public void setacodano(String acodano) {
		this.acodano = acodano;
	}
		
}
