package sv.edu.ues.dsi.palasatenea.modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "materia", catalog = "palasatenea")
public class Materia implements java.io.Serializable {

	private String mcodmateria;
	private Anolectivo anolectivo;
	private Docente docente;
	private String ucarnetusuario;
	private String escarnet;
	private String mnombremateria;
	private int munidadesvalorativas;

	public Materia() {
	}

	public Materia(String mcodmateria, String mnombremateria,
			int munidadesvalorativas) {
		this.mcodmateria = mcodmateria;
		this.mnombremateria = mnombremateria;
		this.munidadesvalorativas = munidadesvalorativas;
	}

	public Materia(String mcodmateria, Anolectivo anolectivo, Docente docente,
			String ucarnetusuario, String escarnet, String mnombremateria,
			int munidadesvalorativas) {
		this.mcodmateria = mcodmateria;
		this.anolectivo = anolectivo;
		this.docente = docente;
		this.ucarnetusuario = ucarnetusuario;
		this.escarnet = escarnet;
		this.mnombremateria = mnombremateria;
		this.munidadesvalorativas = munidadesvalorativas;
	}

	@Id
	@Column(name = "MCODMATERIA", unique = true, nullable = false, length = 8)
	public String getMcodmateria() {
		return this.mcodmateria;
	}

	public void setMcodmateria(String mcodmateria) {
		this.mcodmateria = mcodmateria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACODANO")
	public Anolectivo getAnolectivo() {
		return this.anolectivo;
	}

	public void setAnolectivo(Anolectivo anolectivo) {
		this.anolectivo = anolectivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "DOC_UCARNETUSUARIO", referencedColumnName = "UCARNETUSUARIO"),
			@JoinColumn(name = "DOCCARNET", referencedColumnName = "DOCCARNET") })
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "UCARNETUSUARIO", length = 8)
	public String getUcarnetusuario() {
		return this.ucarnetusuario;
	}

	public void setUcarnetusuario(String ucarnetusuario) {
		this.ucarnetusuario = ucarnetusuario;
	}

	@Column(name = "ESCARNET", length = 8)
	public String getEscarnet() {
		return this.escarnet;
	}

	public void setEscarnet(String escarnet) {
		this.escarnet = escarnet;
	}

	@Column(name = "MNOMBREMATERIA", nullable = false, length = 25)
	public String getMnombremateria() {
		return this.mnombremateria;
	}

	public void setMnombremateria(String mnombremateria) {
		this.mnombremateria = mnombremateria;
	}

	@Column(name = "MUNIDADESVALORATIVAS", nullable = false)
	public int getMunidadesvalorativas() {
		return this.munidadesvalorativas;
	}

	public void setMunidadesvalorativas(int munidadesvalorativas) {
		this.munidadesvalorativas = munidadesvalorativas;
	}

}
