package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 10-21-2014 12:32:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name = "materia", catalog = "palasatenea")
public class Materia implements java.io.Serializable {

	private String mcodmateria;
	private Estudiante estudiante;
	private Anolectivo anolectivo;
	private Docente docente;
	private String mnombremateria;
	private int munidadesvalorativas;

	public Materia() {
	}

	public Materia(String mcodmateria, String mnombremateria,
			int munidadesvalorativas) {
		this.mcodmateria = mcodmateria;
		this.mnombremateria = mnombremateria;
		this.munidadesvalorativas = munidadesvalorativas;
	}

	public Materia(String mcodmateria, Estudiante estudiante,
			Anolectivo anolectivo, Docente docente, String mnombremateria,
			int munidadesvalorativas) {
		this.mcodmateria = mcodmateria;
		this.estudiante = estudiante;
		this.anolectivo = anolectivo;
		this.docente = docente;
		this.mnombremateria = mnombremateria;
		this.munidadesvalorativas = munidadesvalorativas;
	}

	@Id
	@Column(name = "MCODMATERIA", unique = true, nullable = false, length = 8)
	public String getMcodmateria() {
		return this.mcodmateria;
	}

	public void setMcodmateria(String mcodmateria) {
		this.mcodmateria = mcodmateria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "UCARNETUSUARIO", referencedColumnName = "UCARNETUSUARIO"),
			@JoinColumn(name = "ESCARNET", referencedColumnName = "ESCARNET") })
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACODANO")
	public Anolectivo getAnolectivo() {
		return this.anolectivo;
	}

	public void setAnolectivo(Anolectivo anolectivo) {
		this.anolectivo = anolectivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "DOC_UCARNETUSUARIO", referencedColumnName = "UCARNETUSUARIO"),
			@JoinColumn(name = "DOCCARNET", referencedColumnName = "DOCCARNET") })
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "MNOMBREMATERIA", nullable = false, length = 25)
	public String getMnombremateria() {
		return this.mnombremateria;
	}

	public void setMnombremateria(String mnombremateria) {
		this.mnombremateria = mnombremateria;
	}

	@Column(name = "MUNIDADESVALORATIVAS", nullable = false)
	public int getMunidadesvalorativas() {
		return this.munidadesvalorativas;
	}

	public void setMunidadesvalorativas(int munidadesvalorativas) {
		this.munidadesvalorativas = munidadesvalorativas;
	}

}
