package sv.edu.ues.dsi.palasatenea.modelo;

// Generated 10-21-2014 12:32:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Nota generated by hbm2java
 */
@Entity
@Table(name = "nota", catalog = "palasatenea")
public class Nota implements java.io.Serializable {

	private int codnota;
	private Estudiante estudiante;
	private Docente docente;
	private float nnotabimestral;
	private float nnotafinal;
	private float nnota;

	public Nota() {
	}

	public Nota(int codnota, float nnotabimestral, float nnotafinal, float nnota) {
		this.codnota = codnota;
		this.nnotabimestral = nnotabimestral;
		this.nnotafinal = nnotafinal;
		this.nnota = nnota;
	}

	public Nota(int codnota, Estudiante estudiante, Docente docente,
			float nnotabimestral, float nnotafinal, float nnota) {
		this.codnota = codnota;
		this.estudiante = estudiante;
		this.docente = docente;
		this.nnotabimestral = nnotabimestral;
		this.nnotafinal = nnotafinal;
		this.nnota = nnota;
	}

	@Id
	@Column(name = "CODNOTA", unique = true, nullable = false)
	public int getCodnota() {
		return this.codnota;
	}

	public void setCodnota(int codnota) {
		this.codnota = codnota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "UCARNETUSUARIO", referencedColumnName = "UCARNETUSUARIO"),
			@JoinColumn(name = "ESCARNET", referencedColumnName = "ESCARNET") })
	public Estudiante getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(Estudiante estudiante) {
		this.estudiante = estudiante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "DOC_UCARNETUSUARIO", referencedColumnName = "UCARNETUSUARIO"),
			@JoinColumn(name = "DOCCARNET", referencedColumnName = "DOCCARNET") })
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@Column(name = "NNOTABIMESTRAL", nullable = false, precision = 12, scale = 0)
	public float getNnotabimestral() {
		return this.nnotabimestral;
	}

	public void setNnotabimestral(float nnotabimestral) {
		this.nnotabimestral = nnotabimestral;
	}

	@Column(name = "NNOTAFINAL", nullable = false, precision = 12, scale = 0)
	public float getNnotafinal() {
		return this.nnotafinal;
	}

	public void setNnotafinal(float nnotafinal) {
		this.nnotafinal = nnotafinal;
	}

	@Column(name = "NNOTA", nullable = false, precision = 12, scale = 0)
	public float getNnota() {
		return this.nnota;
	}

	public void setNnota(float nnota) {
		this.nnota = nnota;
	}

}
